name: "single account flw"
on:
  workflow_dispatch:
    inputs:
      account:
        description: 'select twitter account name'
        required: true
        default: 'pj_sekai'
        type: choice
        options:
        - pj_sekai
        - bang_dream_gbp
        - Genshin_7
        - wds_game
        - ensemble_stars

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

## scheduled at every hour
##  schedule:
##    - cron: '29 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        if: ${{ inputs.account == 'pj_sekai' }}
        with:
          token: ${{ secrets.FULL_REPO_TOKEN }}
          repository: "popcube/proseka_x"
          path: ./proseka_x
      - uses: actions/setup-node@v4
        with:
          node-version: '>=16.0.0'
          cache: 'npm'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: data extract run
        run: |
          npm install
          npm start           
          ls -la
        env:
          # BEARER_TOKEN: ${{ secrets.TWT_BEARER_TOKEN }}
          ACC_KEY: ${{ secrets.AWS_DYN_ACC_KEY }}
          SEC_ACC_KEY: ${{ secrets.AWS_DYN_SEC_ACC_KEY }}
          ACCOUNT: ${{ inputs.account }}
        
      - name: main run setup
        run: |
          sudo apt-get update
          sudo apt-get install fonts-ipaexfont          
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r ./proseka_x/requirements.txt || :

      - name: data decrypt
        if: ${{ inputs.account == 'pj_sekai' }}
        run: |
          cd ./proseka_x
          python encode_decode.py
        env:
          ENC_DEC: 'DEC'

      - name: main run
        continue-on-error: true
        run: |
          python ./scripts/see_res_1min.py
          python ./scripts/make_stats_1min.py
        env:
          ACCOUNT: ${{ inputs.account }}

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            ./*.csv
            ./*.png
